SELECT XREF_PAYERNAMES.PayerNameId, IIf([XREF_PAYERNAMES].[PayerName]="All","Concept Header",[XREF_PAYERNAMES].[PayerName]) AS PayerName
FROM XREF_PAYERNAMES
WHERE (((XREF_PAYERNAMES.PayerNameId) In (1001,1003,1004,1005,1006,1007,1008,1009,1000)) AND ((XREF_PAYERNAMES.ForUserDisplay)=1))
ORDER BY IIf([XREF_PAYERNAMES].[PayerName]="All","Concept Header",[XREF_PAYERNAMES].[PayerName]);
