RPT_R0045D

Fields
	AccountID Long 4
	CnlyClaimNum Text 30
	AppealDt Text 10
	AppealWk Text 50
	AppealMo Text 50
	AppealStatus Text 2
	Appeallevel Text 50
	AppealSource Text 50
	AppealDecision Memo 0
	AppealDecisionDt Text 10
	AppealPartial Long 4
	AppealReversalAmt Memo 0
	AppealFlagReopen Long 4
	AppealFlagRemand Long 4
	AppealFlagDismiss Long 4
	AppealFlagEscalate Long 4
	AppealFlagBump Long 4
	AppealFlagConflict Long 4
	AppealFlagConflictDW Long 4
	AppealRiskDt Text 10
	MACSource Text 50
	MACDecision Memo 0
	MACDecisionDW Memo 0
	MACDecisionDt Text 10
	MACDecisionDtFix Text 30
	MACLoadDt Text 10
	MACAppealDt Text 10
	MACAppealDtFix Text 30
	MACPromotionDt Text 10
	MACPartial Long 4
	MACReversalAmt Memo 0
	QICSource Text 50
	QICDecision Memo 0
	QICDecisionDW Memo 0
	QICDecisionDt Text 10
	QICDecisionDtFix Text 30
	QICLoadDt Text 10
	QICAppealDt Text 10
	QICAppealDtFix Text 30
	QICPromotionDt Text 10
	QICRemandDt Text 10
	QICPartial Long 4
	QICReversalAmt Memo 0
	ALJSource Text 50
	ALJDecision Memo 0
	ALJDecisionDW Memo 0
	ALJDecisionDt Text 10
	ALJDecisionDtFix Text 30
	ALJLoadDt Text 10
	ALJAppealDt Text 10
	ALJAppealDtFix Text 30
	ALJPromotionDt Text 10
	ALJRemandDt Text 10
	ALJPartial Long 4
	ALJReversalAmt Memo 0
	DABSource Text 50
	DABDecision Memo 0
	DABDecisionDW Memo 0
	DABDecisionDt Text 10
	DABDecisionDtFix Text 30
	DABLoadDt Text 10
	DABAppealDt Text 10
	DABAppealDtFix Text 30
	DABPromotionDt Text 10
	DABRemandDt Text 10
	DABPartial Long 4
	DABReversalAmt Memo 0
	ABN Text 30
	ALJAppealNumber Text 30
	ALJDecisionActual Text 50
	ALJDecisionEntered Text 1
	ALJImageType Text 30
	ALJJudgeName Text 30
	AppealComment Memo 0
	AppealIcn Text 30
	ArStatusCd Text 30
	ArStatusFlow Memo 0
	ArStatusGroupCd Text 30
	DABAppealNumber Text 30
	DABDecisionActual Text 30
	DABDocketNumber Text 30
	EHRFlag Text 30
	FollowOConnorDecision Text 1
	HearingDt Text 20
	HearingMo Text 50
	HearingOTR Text 50
	LastUpdateDt Date/Time 8
	LastUpdateUser Text 30
	NOIRecDt Date/Time 8
	NOISentDate Date/Time 8
	NOIStatus Text 50
	OMHAOffice Text 50
	OTR Text 1
	Participant Text 30
	ParticipatedInHearing Text 50
	PayAncillaryServices Text 1
	PayOutpatientObservServices Text 1
	PS_Summary_Written Text 100
	QICAppealNumber Text 30
	QICDecisionActual Text 50
	RuledOnReopening Text 1
	WaiverOfLiabWithoutFault Text 50
	Withdrawn Text 1
	ALJRequestImageReceivedDt Text 10
	ALJNoticeImageReceivedDt Text 10
	ALJDecisionImageReceivedDt Text 10
	ArSetupAmt Currency 8
	ArSetupDt Text 10
	ClmFromDt Date/Time 8
	DataType Text 5
	ICN Text 30
	MACAppealed Long 4
	MACWin Long 4
	MACLose Long 4
	MACUnder Long 4
	QICAppealed Long 4
	QICWin Long 4
	QICLose Long 4
	QICUnder Long 4
	ALJAppealed Long 4
	ALJWin Long 4
	ALJLose Long 4
	ALJUnder Long 4
	DABAppealed Long 4
	DABWin Long 4
	DABLose Long 4
	DABUnder Long 4
	Appealed Long 4
	AppealWin Long 4
	AppealLose Long 4
	AppealUnder Long 4
	MACAppealedAmt Currency 8
	MACWinAmt Currency 8
	MACLoseAmt Currency 8
	MACUnderAmt Currency 8
	QICAppealedAmt Currency 8
	QICWinAmt Currency 8
	QICLoseAmt Currency 8
	QICUnderAmt Currency 8
	ALJAppealedAmt Currency 8
	ALJWinAmt Currency 8
	ALJLoseAmt Currency 8
	ALJUnderAmt Currency 8
	DABAppealedAmt Currency 8
	DABWinAmt Currency 8
	DABLoseAmt Currency 8
	DABUnderAmt Currency 8
	AppealedAmt Currency 8
	AppealWinAmt Currency 8
	AppealLoseAmt Currency 8
	AppealUnderAmt Currency 8
	MACSafe Long 4
	MACRisk Long 4
	QICSafe Long 4
	QICRisk Long 4
	ALJSafe Long 4
	ALJRisk Long 4
	DABSafe Long 4
	DABRisk Long 4
	MACSafeAmt Currency 8
	MACRiskAmt Currency 8
	QICSafeAmt Currency 8
	QICRiskAmt Currency 8
	ALJSafeAmt Currency 8
	ALJRiskAmt Currency 8
	DABSafeAmt Currency 8
	DABRiskAmt Currency 8
	MACRebillDays Long 4
	QICRebillDays Long 4
	ALJRebillDays Long 4
	DABRebillDays Long 4
	MACRebill Long 4
	QICRebill Long 4
	ALJRebill Long 4
	DABRebill Long 4
	MACRebillAmt Currency 8
	QICRebillAmt Currency 8
	ALJRebillAmt Currency 8
	DABRebillAmt Currency 8
	ReserveBucket Text 33
	ReserveBucketTEST Text 33
	ReserveBucketTEST2 Text 33
	ReserveBucketTest3SafeAppeal Text 8
	ReserveBucketTest3SafeRebill Text 8
	MACSafeTx Text 18
	QICSafeTx Text 18
	ALJSafeTx Text 18
	DABSafeTx Text 18
	MACRebillTx Text 23
	QICRebillTx Text 23
	ALJRebillTx Text 23
	DABRebillTx Text 23
	Rebilled Long 4
	RebilledAmt Currency 8
	MACDecisionMo Text 7
	QICDecisionMo Text 7
	ALJDecisionMo Text 7
	DABDecisionMo Text 7
	MACAppealAgeGroup Text 5
	QICAppealAgeGroup Text 7
	ALJAppealAgeGroup Text 5
	DABAppealAgeGroup Text 5
	AppealDecisionMo Text 7
	RiskDecisionDt Long 4
	ADRLetterDt Text 10
	ADRLetterNum Text 140
	ARRisk Long 4
	ARSetUp Long 4
	ARSetupAge Long 4
	ArSetUpAgeGroup Text 7
	ArSetupMo Text 7
	ARStatus Text 30
	Auditor Text 50
	BeneAge Long 4
	ClmStatus Text 5
	ClmStatusDesc Text 255
	ClmSubStatus Text 50
	ClmSubStatusDesc Text 255
	ClmSubStatusGroup Text 255
	ClmSubStatusGrouping Text 35
	CnlyClaimAmt Currency 8
	Collected Long 4
	CollectedDt Text 10
	ConceptCategory Text 5
	ConceptDesc Memo 0
	ConceptID Text 10
	Contractor Text 20
	DemandLetterDt Text 10
	DiscussAuditor Text 50
	DiscussDisp Text 2
	Discussed Long 4
	DiscussionDecisionDt Text 10
	DiscussionDecisionMo Text 50
	DiscussionDecisionYr Text 50
	DiscussionDt Text 10
	DiscussionMo Text 50
	DiscussionYr Text 50
	DiscussOutcome Text 100
	DiscussSource Text 19
	DRG Text 3
	FinanceGroup Text 20
	GrossID Long 4
	GrossIDOPUP Text 2
	HCPCSCd Memo 0
	ID Long 4
	Invoiced Long 4
	InvoicedDt Text 10
	InvoicedMo Text 7
	LastARorAPStatusDt Text 10
	LastARorAPStatusShrtNm Text 50
	LastDisp Text 100
	LOS Integer 2
	PayerNum Text 5
	ProvName Text 255
	ProvNum Text 16
