REPORT_Stats

Fields
	CnlyClaimNum Text 30
	ICN Text 30
	DataType Text 5
	Part Text 5
	PayerNum Text 5
	PayerName Text 100
	WorkloadID Text 5
	CnlyProvID Text 30
	ProvNum Text 16
	ProvNPI Text 10
	ProvName Text 255
	ProvStCd Text 2
	TaxID Text 30
	Zip3 Text 3
	TaxIDGroup Text 1
	ProviderLimit Long 4
	TaxIdLimit Long 4
	ProvStatus Text 5
	ProvStatusDesc Text 255
	HealthportStatus Text 20
	DRG Text 3
	DRGGroup Text 255
	DRGDesc Text 255
	HCPCSCd Memo 0
	PrincipalDiag Text 7
	LOS Integer 2
	DischargeStatus Text 2
	TOB Text 3
	CAN Text 35
	BIC Text 8
	EquatedBic Text 8
	MedicalRecordNum Text 30
	BeneStCd Text 2
	BeneAge Long 4
	ContractId Long 4
	AuditNum Long 4
	AuditDesc Memo 0
	ReviewType Text 2
	Adj_ReviewType Text 10
	ClaimLevel Text 1
	LOB Text 50
	Team Text 25
	TeamGroup Text 20
	Auditor Text 50
	Adj_Auditor Text 50
	R3User Text 1
	Contractor Text 20
	SubContractor Text 20
	FinanceGroup Text 20
	ClmStatus Text 5
	ClmStatusDesc Text 255
	ClmStatusFlowHoriz Memo 0
	LifeCycleFlowHoriz Memo 0
	LifeCycleArea Text 17
	ClmStatusChangeTime Date/Time 8
	ClmStatusChangeDt Text 10
	ClmStatusChangeUser Text 50
	ClmStatusAge Long 4
	ClmStatusAgeGroup Text 7
	ClmStatusGroup Text 100
	FirstDisp Text 100
	FirstDisp2 Text 100
	LastDisp Text 100
	CurrDisp Text 2
	ClmSubStatusGrouping Text 35
	ClmSubStatusGroup Text 255
	ClmSubStatus Text 50
	ClmSubStatusDesc Text 255
	ClmSubstatusDt Text 10
	ClmSubstatusUser Text 50
	adj_Comments Text 255
	AR_Comments Memo 0
	SentToPayerCheck Text 39
	QueueType Text 5
	QueueTypeDesc Text 255
	ExceptionTypeId Text 5
	ExceptionTypeDesc Text 255
	QueueAuditor Text 50
	QueueEntryDt Date/Time 8
	QueueAssignDt Date/Time 8
	QueueAge Long 4
	QueueAgeGroup Text 7
	ConceptID Text 10
	ConceptDesc Memo 0
	ClientIssueNum Text 50
	ConceptIDHoriz Memo 0
	ConceptReviewType Text 2
	ConceptCatID Long 4
	ConceptCategory Text 5
	ConceptGroup Text 255
	ConceptGroup2 Text 2
	ConceptCat Text 255
	BudgetGroup Text 10
	ConceptAuditor Text 50
	ConceptSource Text 50
	ConceptStatus Text 5
	ConceptStatusDesc Text 100
	ConceptLevel Text 1
	ErrorCd Text 10
	ErrorDesc Memo 0
	ErrorGroupCd Text 255
	ErrorGroupDesc Text 50
	DetailLines Long 4
	DetailConceptCount Long 4
	ConceptsHit Text 4
	ConceptLevelViolation Text 1
	Adj_DRG Text 5
	Adj_DischargeStatus Text 2
	SchedPmtDt Text 10
	SchedPmtMo Text 50
	ClmFromDt Text 10
	ClmThruDt Text 10
	ScopeDt Text 10
	ScopeGroup Text 22
	AddedDt Text 10
	AddedMo Text 7
	AddedYr Text 4
	RequestedDt Text 10
	RequestedMo Text 7
	RequestedYr Text 4
	ReceivedDt Text 10
	FirstReceivedDt Text 10
	ReceivedMo Text 7
	ScanDt Text 10
	ScanMo Text 7
	ScanValidationDt Text 10
	ReviewedDt Text 10
	ReviewedMo Text 7
	ProductivityTime Date/Time 8
	ProductivityDt Text 10
	ProductivityMo Text 7
	ProductivityWk Text 50
	ProductivityYr Text 50
	ProductivityFyr Text 50
	FirstDispDt Text 10
	FirstDispMo Text 7
	FirstDispAuditorDt Text 10
	LastDispDt Text 10
	LastDispMo Text 7
	CreditDt Text 25
	CreditMo Text 25
	CreditDtSwitch Text 25
	SemiAutoLetterDt Text 10
	SemiAutoLetterMo Text 7
	TechDenialLetterDt Text 10
	ResultsLetterDt Text 10
	DemandLetterDt Text 10
	NoFindingsLetterDt Text 10
	ClosedDt Text 10
	SentToPayerDt Text 10
	SentToPayerMo Text 7
	SentToPayerWk Text 50
	SentToPayerYr Text 4
	SentToPayerFyr Text 50
	ARSetupDt Text 10
	ARSetupWk Text 50
	ArSetupMo Text 7
	ARProcessDt Text 10
	ARProcessMo Text 50
	CollectedDt Text 10
	CollectedDt_Invoiced Text 10
	CollectedWk Text 50
	CollectedMo Text 7
	CollectedYr Text 50
	InvoicedDt Text 10
	InvoicedMo Text 7
	PayerAppealDt Text 10
	PayerAppealMo Text 50
	PayerAppealDecisionDt Text 10
	PayerAppealDecisionMo Text 7
	GrossID Long 4
	GrossIDOPUP Text 2
	GrossIDLost Long 4
	GrossConsidered Long 4
	Void Long 4
	IDGroup Text 4
	UnderpayFlag Text 1
	ARSetUpUnderpayFlag Text 1
	ReimbAmtGroup Text 16
	ReimbAmt Currency 8
	ProjectedSavings Currency 8
	DetailProjectedSavings Currency 8
	CnlyClaimAmt Currency 8
	GrossIDAmt Currency 8
	IDAmt Currency 8
	OverpayAmt Currency 8
	UnderpayAmt Currency 8
	SentToPayerAmt Currency 8
	ARSetUpAmt Currency 8
	CollectedAmt Currency 8
	CollectedAmt_Invoiced Currency 8
	CollectedAmt_NotInvoiced Currency 8
	InvoicedAmt Currency 8
	FeeCreditAmt Currency 8
	FeeAdjustAmt Currency 8
	FeePayback Long 4
	FeeNetAmt Currency 8
	InvoiceReserveAmt Currency 8
	ClosedAmt Currency 8
	Adj_To Text 30
	ARNum Text 50
	ARICN Text 30
	ARICN_Adj_To Text 30
	SentToPayerAge Long 4
	SentToPayerAgeGroup Text 7
	ARSetupAge Long 4
	ArSetUpAgeGroup Text 7
	Udad Long 4
	ArStatus Text 30
	ArStatus2 Text 30
	ArLifeCycle Text 30
	SentToPayerGroup Text 30
	SentToPayerCount Long 4
	FirstSentToPayerDt Text 10
	LastSentToPayerDt Text 10
	RetractionCount Long 4
	LastRetractionDt Text 10
	LastSubmissionCd Text 4
	LastSubmissionDt Text 10
	FeePaybackType Text 10
	Invoiceable Long 4
	LastretractionFile Text 100
	RetractionAge Long 4
	RetractionAgeGroup Text 7
	DiscussSource Text 19
	Discussed Long 4
	DiscussionYr Text 50
	DiscussionMo Text 50
	DiscussionDt Text 10
	DiscussionDecisionYr Text 50
	DiscussionDecisionMo Text 50
	DiscussionDecisionDt Text 10
	DiscussAuditor Text 50
	DiscussOutcome Text 100
	DiscussDisp Text 2
	UnderDiscuss Long 4
	DiscussDenied Long 4
	DiscussApproved Long 4
	AppealFlag Long 4
	PayerAppealStatus Memo 0
	PayerAppealLevel Text 50
	PayerAppealDecisionText Long 4
	PayerAppealReason Long 4
	PayerAppealReversalAmt Long 4
	ReopenedAfterLastDecision Long 4
	PayerAppealOutcomeSource Text 50
	RiskDemandDt Long 4
	RiskLostInvoiced Long 4
	ARRisk Long 4
	UnderAppealAmt Currency 8
	ScanOperator Text 50
	ReceivedMeth Text 10
	ScanPaidPages Long 4
	ScanPages Long 4
	ScanPaidAmt Currency 8
