RPT_R0045MG

Fields
	CnlyClaimNum Text 30
	ICN Text 30
	PayerName Text 100
	AppealLevel Text 50
	AppealSource Text 50
	RawDecision Memo 0
	Decision Memo 0
	ArSetupDt Text 10
	AppealDt Text 10
	LoadDt Text 10
	DecisionDt Text 10
	DecisionDtSort Text 10
	SourceFile Memo 0
	Partial Long 4
	Reopen Text 1
	Remand Text 1
	Dismiss Text 1
	Escalate Text 1
	Bump Long 4
	Conflict Long 4
	ConflictDW Long 4
	RankDecision Text 255
	AppealStatus Text 2
	AppealDtUsed Text 10
	DecisionDtUsed Text 10
	MACAppealDt Text 10
	MACAppealDtFix Text 30
	MACDecision Memo 0
	MACDecisionDt Text 10
	MACDecisionDtFix Text 30
	QICAppealDt Text 10
	QICAppealDtFix Text 30
	QICDecision Memo 0
	QICDecisionDt Text 10
	QICDecisionDtFix Text 30
	ALJAppealDt Text 10
	ALJAppealDtFix Text 30
	ALJDecision Memo 0
	ALJDecisionDt Text 10
	ALJDecisionDtFix Text 30
	DABAppealDt Text 10
	DABAppealDtFix Text 30
	DABDecision Memo 0
	DABDecisionDt Text 10
	DABDecisionDtFix Text 30
