v_QA_Review_Worktable_Submitted

Fields
	CnlyClaimNum Text 30
	SeqNo Long 4
	ICN Text 30
	DataType Text 5
	ClmStatus Text 5
	PrevClmStatus Text 5
	Auditor Text 50
	AuditTeam Text 50
	CompanyID Byte 1
	ConceptID Text 10
	MRReceivedDt Date/Time 8
	QueueType Text 5
	QueueTypeDescription Text 255
	QueueEntryDt Date/Time 8
	InactiveDays Long 4
	MedicalNecessity Text 1
	DRG Text 3
	Adj_DRG Text 5
	ClmTotalChgs Currency 8
	ReimbAmt Currency 8
	Adj_ProjectedSavings Currency 8
	CnlyProvID Text 30
	ProvName Text 255
	MemberName Text 40
	MemberDOB Date/Time 8
	QAStatus Text 20
	QAScore Long 4
	RationaleCorrect Text 1
	DRGCorrectDecision Text 1
	DRGCorrect Text 1
	DRGCorrectDischarge Text 1
	DRGCodingChange Text 1
	DRGClaimReferMN Text 2
	MNPertLab Text 1
	MNPhysOrder Text 1
	MNCompleteMR Text 1
	MNGrammar Text 1
	MNCorrectDecision Text 1
	MNCodingCorrect Text 2
	RationaleCorrect_Comment Memo 0
	DRGCorrectDecision_Comment Memo 0
	DRGCorrect_Comment Memo 0
	DRGCorrectDischarge_Comment Memo 0
	DRGCodingChange_Comment Memo 0
	DRGClaimReferMN_Comment Memo 0
	MNPertLab_Comment Memo 0
	MNPhysOrder_Comment Memo 0
	MNCompleteMR_Comment Memo 0
	MNGrammar_Comment Memo 0
	MNCorrectDecision_Comment Memo 0
	MNCodingCorrect_Comment Memo 0
	ReviewComment Memo 0
	Reviewer Text 50
	ReviewedDate Date/Time 8
	SubmitComment Memo 0
	SubmitBy Text 50
	SubmitDate Date/Time 8
	LockUser Text 50
	LockDt Date/Time 8
	ClaimPayerNum Text 5
	CurPayerName Text 50
	AHClmstatus Text 5
	AHAdjRationale Text 1
	Adj_ReviewType Text 10
	Alert Text 8
	ExceptionType Text 5
	ExceptionDesc Text 255
	Report_Stats_Score_Group Long 4
