v_QUEUE_Exception

Fields
	MRReceived_Age Long 4
	ReconReceived_Age Long 4
	ReconReceived_Date Date/Time 8
	LOB Text 50
	CnlyClaimNum Text 30
	ICN Text 30
	PayerNum Text 5
	PayerName Text 50
	ExceptionType Text 5
	ExceptionDesc Text 255
	ExceptionStatus Text 10
	ExceptionEntryDt Date/Time 8
	ExceptionAgeGroup Text 15
	Adj_ConceptID Text 10
	Adj_ReviewType Text 10
	DataType Text 5
	AuditNum Long 4
	QueueType Text 5
	QueueStatus Text 10
	CnlyProvID Text 16
	CreateDt Date/Time 8
	AssignedFrom Text 50
	AssignedTo Text 50
	AssignedDate Date/Time 8
	TotalChargeAmt Currency 8
	TotalReimbAmt Currency 8
	Adj_ProjectedSavings Currency 8
	NextReviewDt Date/Time 8
	MaxThresholdDt Date/Time 8
	LastUpdate Date/Time 8
	UpdateUser Text 50
	NoteID Long 4
	AccountID Long 4
	CompanyName Text 100
	TotAROrAPAmt Currency 8
	TotARAdjAmt Currency 8
	NetAROrAPAmt Currency 8
	TotPrincRecovOrPaidAmt Currency 8
	TotInvoiceFeeAmt Currency 8
	CollBalanceAmt Currency 8
	CollFeeBalanceAmt Currency 8
	IDAmt Currency 8
	IDVarianceAmt Currency 8
	IDVariancePct Currency 8
	IDVariancePctGrp Text 7
	IDVariancePctDtlGrp Text 24
