REPORT_Budget

Fields
	BudgetMo Text 255
	FiscalYr Text 4
	Reviewed_DRG Double 8
	Reviewed_MN Double 8
	IDPerChart_DRG Currency 8
	IDPerChart_MN Currency 8
	IDPerChart_CX Currency 8
	ID_DRG Currency 8
	ID_MN Currency 8
	ID_AUTO Currency 8
	ID_SEMI Currency 8
	Underpay Currency 8
	SentToPayer Currency 8
	ARSetup Currency 8
	Revenue Currency 8
	ScanCost Currency 8
	Labor Currency 8
	Contractor Currency 8
	Rent Currency 8
	Other Currency 8
	Revenue_Actual Currency 8
	ScanCost_Actual Currency 8
	Labor_Actual Currency 8
	Contrator_Actual Currency 8
	Rent_Actual Currency 8
	Other_Actual Currency 8
	ID_TECH Currency 8
	Reviewed_MN_AWAC Double 8
	Reviewed_MN_MRC Double 8
	Reviewed_MN_NJPR Double 8
	Reviewed_MN_NURAD Double 8
	Reviewed_MN_CNLY Double 8
	IDPerChart_MN_SUB Currency 8
	IDPerChart_MN_INT Currency 8
	ID_PHARM Currency 8
	Reviewed_PHARM Double 8
	Reviewed_MN_SUB Double 8
	HIT_MN_CNLY Double 8
	HIT_MN_SUB Double 8
	HIT_DRG Double 8
	HIT_CX Double 8
	CNV Double 8
	CNV_MN Double 8
	CNV_DRG Double 8
	CNV_PHARM Double 8
	CNV_TECH Double 8
	CNV_AUTO Double 8
	CNV_SEMI Double 8
	IDPerChart_PHARM Currency 8
	HIT_PHARM Double 8
	Reviewed_MN_NRAC Double 8
	Reviewed_IRF Double 8
	Reviewed_HH Double 8
	IDPerChart_IRF Double 8
	IDPerChart_HH Double 8
	HIT_IRF Double 8
	HIT_HH Double 8
