APPEAL_Prod_History

Fields
	CnlyClaimNum Text 30
	AppealLevel Byte 1
	AppealOutcome Text 10
	ReversalAmt Currency 8
	ReversalReason Memo 0
	AppealSource Text 50
	SFileName Text 255
	Icn Text 30
	LastUpdateDt Date/Time 8
	LastUpdateUser Text 30
	ManualEventEntry Boolean 1
	Payer Text 30
	AppealDt Date/Time 8
	DecisionDt Date/Time 8
	LoadDt Date/Time 8
	AppealIcn Text 30
	AppealComment Memo 0
	ALJJudgeName Text 30
	QICAppealNumber Text 30
	ALJAppealNumber Text 30
	PromotionDt Date/Time 8
	PayOutpatientObservServices Text 1
	PayAncillaryServices Text 1
	FollowOConnorDecision Text 1
	RuledOnReopening Text 1
	WaiverOfLiabWithoutFault Text 50
	ALJDecisionActual Text 50
	EHRFlag Text 100
	NOISentDate Date/Time 8
	HearingDt Date/Time 8
	NOHRecDt Date/Time 8
	ParticipatedInHearing Text 50
	ReOpenInd Text 5
	DismissalInd Text 5
	Participant Text 30
	ABN Boolean 1
	NOIStatus Text 50
	HearingOTR Text 50
	ALJDecisionEntered Boolean 1
	OTR Boolean 1
	Withdrawn Boolean 1
	PS_Summary_Written Text 100
