v_CONCEPT_ValidationSummary_Header

Fields
	CnlyClaimNum Text 30
	DataType Text 5
	PayerNum Text 5
	ICN Text 30
	OriginalICN Text 30
	QueryCd Text 1
	ProvNum Text 16
	CnlyProvID Text 30
	ProvStCd Text 2
	ProvSpecCd Text 5
	ProvNPI Text 10
	MedicalRecordNum Text 30
	PatCtlNum Text 38
	CAN Text 35
	BIC Text 8
	EquatedBIC Text 8
	BeneBirthDt Date/Time 8
	BeneStCD Text 2
	BeneSexCd Text 1
	BeneRaceCd Text 1
	PatSurname Text 30
	PatFirstInit Text 30
	PatMidInit Text 1
	NCHPatientStatus Text 1
	DRG Text 3
	AdmitDiag Text 7
	PrincipalDiag Text 7
	LOS Integer 2
	IPAdmitType Text 1
	IPAdmitDate Date/Time 8
	IPDischargeDt Date/Time 8
	ClmFromDt Date/Time 8
	ClmThruDt Date/Time 8
	SchedPmtDt Date/Time 8
	PayerReceiptDt Date/Time 8
	ClmTotalChgs Currency 8
	AllowedChgAmt Currency 8
	ReimbAmt Currency 8
	ProvPdAmt Currency 8
	BenePdAmt Currency 8
	COBAmt Currency 8
	COBCarrierCd Text 1
	Deductible Currency 8
	BeneCoins Currency 8
	DRGOutlierPmt Currency 8
	DischargeStatus Text 2
	ClmDispositionCd Text 5
	TOB Text 3
	ClmFreqCd Text 1
	OpTransType Text 1
	IPOutlierIndicator Text 1
	AttendingPhysician Text 16
	AttendingNPI Text 10
	OprtgUPIN Text 6
	OprtgNPI Text 16
	ReferPhysUPIN Text 6
	ReferPhysNPI Text 10
	OrderingUPIN Text 6
	OrderingNPI Text 10
	OthProvUPIN Text 6
	OthProvNPI Text 10
	ECode Text 7
	Adj_ProjectedSavings Currency 8
	ConceptID Text 10
