AUDITCLM_Dtl

Fields
	CnlyClaimNum Text 30
	ICN Text 30
	LineNum Long 4
	LnProvNum Text 16
	LnProvNPI Text 10
	LnProvSt Text 2
	LnProvSpecialty Text 5
	LnHCFASpecCd Text 3
	LnGroupNPI Text 10
	LnProvTIN Text 9
	LnClmFromDt Date/Time 8
	LnClmThruDt Date/Time 8
	RevDt Date/Time 8
	LnPOS Text 2
	LnDiagCd Text 7
	RevCd Text 4
	HCPCSCd Text 5
	Mod01 Text 2
	Mod02 Text 2
	Mod03 Text 2
	Mod04 Text 2
	Mod05 Text 2
	AnsiCd01 Text 5
	AnsiCd02 Text 5
	AnsiCd03 Text 5
	AnsiCd04 Text 5
	Units Long 4
	UnitType Text 1
	ChargePerUnit Currency 8
	AnesthesiaBaseUnitCt Long 4
	BetosCd Text 5
	NDC Text 11
	LnReimbAmt Currency 8
	LnChargeAmt Currency 8
	LnAllowedAmt Currency 8
	LnNonCoveredAmt Currency 8
	LnBenePdAmt Currency 8
	LnCoinsAmt Currency 8
	LnCOBAmt Currency 8
	DMEPurchasePrice Currency 8
	ClmGuid Guid 16
	DataType Text 5
	Adj_HCPCS Text 5
	Adj_Units Long 4
	Adj_ProjectedSavings Currency 8
	Adj_Ind Text 1
	Adj_ConceptID Text 10
	Adj_VulnerabilityCd Text 10
	Adj_ReimbAmt Currency 8
	AutoID Long 4
	lnRecoveryAmt Currency 8
	Adj_Mod01 Text 2
	Adj_Mod02 Text 2
	Adj_Mod03 Text 2
	Adj_Mod04 Text 2
	Adj_Mod05 Text 2
	RecoveryReason Long 4
	LLCategory Text 5
	Adj_RevCd Text 4
	ConceptHit Text 4
	NOCCode Text 14
	OccurCds Text 4
	OccurDts Text 14
