v_COLL_Hdr

Fields
	CnlyClaimNum Text 30
	OverpaymentType Text 1
	WorkloadID Text 5
	OrigWorkloadID Text 5
	BusSegID Text 4
	ProvNPI Text 10
	ProvNum Text 30
	OriginalICN Text 30
	AdjICN Text 30
	OrigClaimPaidDt Date/Time 8
	AdjClaimPaidDt Date/Time 8
	AROrAPNum Text 50
	AROrAPDt Date/Time 8
	ActivityTypeCd Text 30
	ActivityTypeShrtNm Text 50
	ActivityTypeDomainCd Text 25
	ActivityNum Text 30
	ActivityDt Date/Time 8
	ActivityAmt Currency 8
	PrincRecovOrPaidAmt Currency 8
	IntRecovOrPaidAmt Currency 8
	CurPrincipleAmt Currency 8
	CurBalanceAmt Currency 8
	AROrAPStatusCd Text 50
	AROrAPStatusShrtNm Text 50
	AROrAPStatusDomainCd Text 25
	AROrAPStatusDt Date/Time 8
	TransID Text 30
	CrossRefAROrAPNum Text 50
	RACDWPayTypeCd Text 15
	RACDWPayTypeShrtNm Text 30
	RACDWInvClassCd Text 15
	RACDWInvClassShrtNm Text 30
	BankruptInd Text 1
	ClaimSystemCd Text 25
	SourceSystemCd Text 25
	ContractID Long 4
	CnlyARCollID Text 120
	CnlyClaimARID Text 30
	DocGUID Guid 16
	AutoId Long 4
	FileTypeCd Text 20
	FileTypeVersCd Text 10
	SFileName Text 255
	SFileDate Date/Time 8
	BatchPrcsDt Date/Time 8
	CreateDt Date/Time 8
	LastUpDt Date/Time 8
	LastUpUser Text 50
