AR_SETUP_Hdr

Fields
	CnlyClaimNum Text 30
	DocGUID Guid 16
	AutoId Long 4
	SFileName Text 255
	FileDate Date/Time 8
	BatchPrcsDt Date/Time 8
	MultiLoadInd Byte 1
	OverpaymentType Text 1
	BeneStCD Text 2
	ARICN Text 30
	ARICN_Adj_To Text 30
	ARNum Text 50
	OrigReimbAmt Currency 8
	Adj_ReimbAmt Currency 8
	Adj_Dt Date/Time 8
	Adj_RecoveryAmt Currency 8
	PayerReasonCode Text 25
	ProvNum Text 30
	ProvNPI Text 10
	OrderingUPIN Text 6
	OrderingNPI Text 10
	PayerNum Text 16
	Adj_ClosedDt Date/Time 8
	AccountID Long 4
	WorkloadID Text 5
	HCPCSPayloadTypeCd Text 30
	HCPCSPayloadCnt Long 4
	HCPCSPayload Memo 0
	CnlyClaimARID Text 30
	FileTypeCd Text 20
	FileTypeVersCd Text 10
	AROrAPStatusCd Text 50
	AROrAPStatusDomainCd Text 25
	LastUpDt Date/Time 8
	LastUpUser Text 50
	SourceID Text 5
	AdjDRG Text 3
	ProvBillNPI Text 10
	ProvBillNum Text 16
	VoidInd Long 4
	TransID Text 15
	BankruptInd Text 1
	ContractID Long 4
