AUDITCLM_Hdr

Fields
	CnlyClaimNum Text 30
	DataType Text 5
	PayerNum Text 5
	ICN Text 30
	OriginalICN Text 30
	QueryCd Text 1
	ProvNum Text 16
	CnlyProvID Text 30
	ProvStCd Text 2
	ProvSpecCd Text 5
	ProvNPI Text 10
	MedicalRecordNum Text 30
	PatCtlNum Text 38
	CAN Text 35
	BIC Text 8
	EquatedBIC Text 8
	BeneBirthDt Date/Time 8
	BeneStCD Text 2
	BeneSexCd Text 1
	BeneRaceCd Text 1
	PatSurname Text 30
	PatFirstInit Text 30
	PatMidInit Text 1
	NCHPatientStatus Text 1
	DRG Text 3
	AdmitDiag Text 7
	PrincipalDiag Text 7
	LOS Integer 2
	IPAdmitType Text 1
	IPAdmitDate Date/Time 8
	IPDischargeDt Date/Time 8
	ClmFromDt Date/Time 8
	ClmThruDt Date/Time 8
	SchedPmtDt Date/Time 8
	PayerReceiptDt Date/Time 8
	ClmTotalChgs Currency 8
	AllowedChgAmt Currency 8
	ReimbAmt Currency 8
	ProvPdAmt Currency 8
	BenePdAmt Currency 8
	COBAmt Currency 8
	COBCarrierCd Text 1
	Deductible Currency 8
	BeneCoins Currency 8
	DRGOutlierPmt Currency 8
	DischargeStatus Text 2
	ClmDispositionCd Text 5
	TOB Text 3
	ClmFreqCd Text 1
	OpTransType Text 1
	IPOutlierIndicator Text 1
	AttendingPhysician Text 16
	AttendingNPI Text 10
	OprtgUPIN Text 6
	OprtgNPI Text 16
	ReferPhysUPIN Text 6
	ReferPhysNPI Text 10
	OrderingUPIN Text 6
	OrderingNPI Text 10
	OthProvUPIN Text 6
	OthProvNPI Text 10
	ECode Text 7
	LoadDt Date/Time 8
	ClmGuid Guid 16
	Adj_AuditNum Long 4
	Adj_Auditor Text 50
	Adj_ReviewType Text 10
	Adj_ConceptID Text 10
	Adj_VulnerabilityCd Text 10
	Adj_DRG Text 5
	Adj_ProjectedSavings Currency 8
	Adj_RecoveryAmt Currency 8
	Adj_Can Text 30
	Adj_Bic Text 8
	Adj_From Text 30
	Adj_To Text 30
	Adj_CreateDate Date/Time 8
	Adj_SentToPayerDt Date/Time 8
	Adj_ClosedDt Date/Time 8
	Adj_ReimbAmt Currency 8
	Adj_DischargeStatus Text 2
	Adj_Rationale Memo 0
	Adj_ChartOutcome Text 1
	Adj_ChartReviewDt Date/Time 8
	ClmStatus Text 5
	LastUpDt Date/Time 8
	LastUpUser Text 50
	LockDt Date/Time 8
	LockUserID Text 50
	HoldStatus Text 1
	HoldReason Text 5
	HoldDate Date/Time 8
	HoldUser Text 50
	NoteID Long 4
	AutoID Long 4
	ValidationInd Text 10
	AccountID Long 4
	SrcPlatform Text 50
	LOB Text 50
	CheckedOut Boolean 1
	CheckedOutUser Text 255
	CheckedOutDate Date/Time 8
	ICDVersionCdFlag Integer 2
	ContractID Long 4
