v_SCREEN_TabDtl

Fields
	Can Text 16
	BIC Text 2
	EquatedBic Text 2
	DataType Text 5
	Icn Text 23
	LineNum Text 255
	RevCd Text 4
	HCPCSCd Text 5
	HCPCSShortDescription Text 100
	Mod01 Text 2
	Mod02 Text 2
	Mod03 Text 2
	Mod04 Text 2
	Mod05 Text 2
	LnDiagCd Text 7
	LnDiagVrsnCd Text 1
	Units Decimal 16
	LnReimbAmt Currency 8
	LnChargeAmt Currency 8
	LnAllowedAmt Currency 8
	LnTypSvcCd Text 2
	RevDt Date/Time 8
	LnPOS Text 2
	LnProvNum Text 10
	LnProvNpi Text 10
	LnProvSt Text 2
	LnProvSpecialty Text 2
	LnHcfaSpecCd Text 2
	LnGroupNpi Text 10
	LnProvTin Text 10
	LnClmFromDt Date/Time 8
	LnClmThruDt Date/Time 8
	AnsiCd01 Text 5
	AnsiCd02 Text 5
	AnsiCd03 Text 5
	AnsiCd04 Text 5
	UnitType Text 1
	ChargePerUnit Currency 8
	AnesthesiaBaseUnitCt Long 4
	BetosCd Text 5
	NDC Text 24
	LnNonCoveredAmt Currency 8
	LnBenePdAmt Currency 8
	LnCoinsAmt Currency 8
	LnCOBAmt Currency 8
	DMEPurchasePrice Currency 8
	RevCntrDedCoinsCd Text 1
	CnlyClaimNum Text 30
	RevConsolidatedBillCd Text 2
	LnSvcsCt Decimal 16
	BenePartBDedAmt Currency 8
	CarrDupCheck Text 1
	ProvZip Text 9
	ParInd Text 1
	LineConsBillingIndCd Text 1
	AddlClmDocIndCd Text 1
	RdcdPmtAsstCd Text 1
	SchedPmtDt Date/Time 8
