v_Appeal_TIMELINE

Fields
	CnlyClaimNum Text 30
	Icn Text 30
	AppealIcn Text 30
	AppealLevel Byte 1
	AppealLevelDescription Text 50
	AppealDt Date/Time 8
	AppealOutcome Text 10
	DecisionDt Date/Time 8
	ReversalAmt Currency 8
	ReversalReason Memo 0
	AppealSource Text 50
	Payer Text 30
	SFileName Text 255
	AppealComment Memo 0
	QICAppealNumber Text 30
	ALJAppealNumber Text 30
	ALJJudgeName Text 30
	PromotionDt Date/Time 8
	NOHRecDt Date/Time 8
	HearingDt Date/Time 8
	NOISentDate Date/Time 8
	ALJDecisionActual Text 50
	PayOutpatientObservServices Text 1
	PayAncillaryServices Text 1
	FollowOConnorDecision Text 1
	RuledOnReopening Text 1
	WaiverOfLiabWithoutFault Text 50
	ParticipatedInHearing Text 50
	Participant Text 30
	EHRFlag Text 100
	ABN Text 14
	LastUpdateDt Date/Time 8
	LastUpdateUser Text 30
	NOIStatus Text 50
	HearingOTR Text 50
	ALJDecisionEntered Boolean 1
	OTR Boolean 1
	Withdrawn Boolean 1
	PS_Summary_Written Text 100
