rpt_R0000S22B

Fields
	ProvNum Text 16
	ProvName Text 255
	Added Long 4
	Validation Long 4
	Limbo Long 4
	Requested Long 4
	WaitForChart Long 4
	Received Long 4
	UnderReview Long 4
	Reviewed Long 4
	ReviewedNet Long 4
	Hold Long 4
	Reject Long 4
	NonRecovery Long 4
	Underpay Long 4
	Overpay Long 4
	GrossId Long 4
	GrossIdAmt Currency 8
	GrossIDLost Long 4
	GrossIDLostAmt Currency 8
	ID Long 4
	IDAmt Currency 8
	UnderpayAmt Currency 8
	OverpayAmt Currency 8
	IDPct Decimal 16
	IDPerClaim Decimal 16
	IDPerReviewed Decimal 16
	FeePerHour Decimal 16
	ScanCostPerClaim Currency 8
	ChartsPerHour Text 38
	GrossMargin Currency 8
	SentToPayer Long 4
	SentToPayerAmt Currency 8
	AtPayer Long 4
	AtPayerAmt Currency 8
	ArSetUp Long 4
	ArSetUpAmt Currency 8
	Collected Long 4
	CollectedAmt Currency 8
	Invoiced Long 4
	InvoicedAmt Currency 8
	Discussed Long 4
	UnderDiscuss Long 4
	DiscussDenied Long 4
	DiscussApproved Long 4
	DiscussedPct Decimal 16
	AppealedPct Decimal 16
	AppealsDecidedPct Decimal 16
	AppealsLostPct Decimal 16
	AppealImpactPct Decimal 16
	GrossIdOP Long 4
	GrossIdOPAmt Currency 8
	GrossIdUP Long 4
	GrossIdUPAmt Currency 8
