RPT_R0045MF

Fields
	CnlyClaimNum Text 30
	CURSource Text 50
	CURLevel Text 50
	CURDecision Memo 0
	CURDecisionDt Text 10
	CURPartial Long 4
	CURReversalAmt Memo 0
	AppealLevel Text 50
	AppealSource Text 50
	RawICN Memo 0
	RawAppealICN Memo 0
	ICN Text 30
	RawPayerName Memo 0
	PayerName Text 100
	RawDecisionLevel Memo 0
	RawDecisionReason Memo 0
	RawDecision Memo 0
	Decision Memo 0
	DecisionMapped Long 4
	RawAppealDt Memo 0
	ARSetupDt Text 10
	AppealDt Text 10
	PromotionDt Text 10
	RawDecisionDt Memo 0
	DecisionDt Text 10
	DecisionDtSort Text 10
	RankSource Long 4
	RankDecision Text 255
	RawLoadDt Memo 0
	LoadDt Text 10
	ReOpen Text 1
	Remand Text 1
	Dismiss Text 1
	Escalate Text 1
	RawReversalAmt Memo 0
	ReversalAmt Memo 0
	SourceFile Memo 0
	Partial Long 4
	Bump Long 4
	Conflict Long 4
	ConflictDw Long 4
	MACAppealDt Text 10
	MACDecision Memo 0
	MACDecisionDt Text 10
	MACSource Text 50
	QICAppealDt Text 10
	QICDecision Memo 0
	QICDecisionDt Text 10
	QICSource Text 50
	ALJAppealDt Text 10
	ALJDecision Memo 0
	ALJDecisionDt Text 10
	ALJSource Text 50
	DABAppealDt Text 10
	DABDecision Memo 0
	DABDecisionDt Text 10
	DABSource Text 50
	MACDecisionDtFix Text 13
	QICDecisionDtFix Text 13
	ALJDecisionDtFix Text 13
	DABDecisionDtFix Text 13
	MACAppealDtFix Text 11
	QICAppealDtFix Text 13
	ALJAppealDtFix Text 14
	DABAppealDtFix Text 13
	ABN Text 30
	ALJAppealNumber Text 30
	ALJDecisionActual Text 50
	ALJDecisionEntered Text 1
	ALJJudgeName Text 30
	AppealComment Memo 0
	AppealIcn Text 30
	ArStatusGroupCd Text 30
	ArStatusCd Text 30
	ArStatusFlow Memo 0
	DABDecisionActual Text 30
	DABAppealNumber Text 30
	DABDocketNumber Text 30
	EHRFlag Text 30
	FollowOConnorDecision Text 1
	HearingDt Date/Time 8
	HearingOTR Text 50
	LastUpdateDt Date/Time 8
	LastUpdateUser Text 30
	NOIRecDt Date/Time 8
	NOISentDate Date/Time 8
	NOIStatus Text 50
	OMHAOffice Text 50
	OTR Text 1
	Participant Text 30
	ParticipatedInHearing Text 50
	PayAncillaryServices Text 1
	PayOutpatientObservServices Text 1
	PS_Summary_Written Text 100
	QICAppealNumber Text 30
	RuledOnReopening Text 1
	WaiverOfLiabWithoutFault Text 50
	Withdrawn Text 1
	Pass1Status Text 2
	Pass1DecisionDt Text 10
	Pass1Source Text 50
	AppealStatus Text 2
	AppealDtUsed Text 10
	DecisionDtUsed Text 10
