v_LDGR_Dtl_Entries

Fields
	ICN Text 30
	ClmStatus Text 5
	DataType Text 5
	Adj_ReviewType Text 10
	LdgrDtlID Guid 16
	CnlyClaimNum Text 30
	AutoId Long 4
	LdgrCreateDt Date/Time 8
	LdgrLastUpDt Date/Time 8
	LdgrLastUpUser Text 50
	OverpaymentType Text 1
	WorkloadID Text 5
	OriginalICN Text 30
	AdjICN Text 30
	AROrAPNum Text 50
	LdgrTransGroupCd Text 30
	LdgrTransTypeCd Text 50
	LdgrTransTypeShrtNm Text 50
	CreditOrDebitCd Text 1
	ActivityTypeCd Text 30
	ActivityTypeDomainCd Text 25
	ActivityTypeShrtNm Text 50
	CnlyActivityTypeCd Text 30
	LdgrTransAmt Currency 8
	LdgrTransDt Date/Time 8
	LdgrTransCrossRefID Text 120
	TransID Text 30
	LdgrNoteTxt Text 255
	VoidInd Byte 1
	DeleteInd Byte 1
	LdgrCrossRefLdgrLastUpDt Date/Time 8
	FeeRt Single 4
	PrincRecovOrPaidAmt Currency 8
	LdgrEntryFeeAmt Currency 8
	CollBalanceAmt Currency 8
	CollFeeBalanceAmt Currency 8
	Rac_Rate Text 9
