v_SCREEN_INT_HDR_ALL

Fields
	Exclusion Text 1
	DRG Text 3
	ICN Text 23
	AdmitDiag Text 7
	AdmitDiagVrsnCd Text 1
	PrincipalDiag Text 7
	PrincipalDiagVrsnCd Text 1
	ClmFromDt Date/Time 8
	ClmThruDt Date/Time 8
	LOS Long 4
	DischargeStatus Text 2
	TOB Text 3
	ClmTotalChgs Currency 8
	ReimbAmt Currency 8
	SchedPmtDt Date/Time 8
	MedicalRecordNum Text 17
	PatCtlNum Text 20
	Can Text 16
	Bic Text 2
	HIC Text 18
	EquatedBic Text 2
	BeneBirthDt Date/Time 8
	ProvNum Text 16
	PayerNum Text 5
	ClmDispositionCd Text 2
	OriginalIcn Text 23
	BeneStCD Text 2
	BeneSexCd Text 1
	ProvStCd Text 2
	AllowedChgAmt Currency 8
	AttendingNpi Text 10
	AttendingPhysician Text 16
	BeneCoins Currency 8
	BenePdAmt Currency 8
	BeneRaceCd Text 1
	cnlyProvID Text 30
	CobAmt Currency 8
	CobCarrierCd Text 1
	Deductible Currency 8
	DrgOutlierPmt Currency 8
	ECode Text 7
	ECodeVrsnCd Text 1
	IPAdmitDt Date/Time 8
	IpAdmitType Text 1
	IPDischargeDt Date/Time 8
	IPOutlierIndicator Text 1
	NchPatientStatus Text 1
	OprtgNpi Text 16
	OprtgUpin Text 16
	OpTransType Text 1
	OrderingNPI Text 10
	OrderingUPIN Text 6
	OthProvNpi Text 10
	OthProvUpin Text 6
	PatFirstInit Text 1
	PatMidInit Text 1
	PatSurname Text 6
	PayerReceiptDt Date/Time 8
	ProvNpi Text 10
	ProvPdAmt Currency 8
	ProvSpecCd Text 5
	QueryCd Text 1
	ReferPhysNPI Text 10
	ReferPhysUpin Text 6
	CnlyClaimNum Text 30
	DataType Text 5
	LoadDt Date/Time 8
	IpAdmitSource Text 1
	TrtmtAuth Text 18
	ProvName Text 255
	ContractId Long 4
