AUDITCLM_INT_Extracts

Fields
	Icn Text 23
	LineNum Long 4
	ClmTotalChgs Currency 8
	AllowedChgAmt Currency 8
	ReimbAmt Currency 8
	ProvPdAmt Currency 8
	BenePdAmt Currency 8
	LnChargeAmt Currency 8
	LnReimbAmt Currency 8
	LnPdPct Currency 8
	PctTotal Currency 8
	PayerNum Text 16
	ProvNum Text 16
	ProvNpi Text 10
	ProvStCd Text 2
	LnProvNum Text 10
	LnProvNpi Text 10
	LnState Text 2
	MedicalRecordNum Text 17
	PatCtlNum Text 20
	Can Text 9
	Bic Text 2
	EquatedBic Text 2
	HIC Text 18
	BeneBirthDt Date/Time 8
	SexCd Text 1
	ClmFromDt Date/Time 8
	ClmThruDt Date/Time 8
	LOS Long 4
	LnClmFromDt Date/Time 8
	LnClmThruDt Date/Time 8
	LnLOS Long 4
	SchedPmtDt Date/Time 8
	AdmitDiag Text 7
	PrincipalDiag Text 16
	DischargeStatus Text 2
	LnDiagCd Text 7
	RevCd Text 4
	HCPCSCd Text 5
	UnitType Text 1
	Units Decimal 16
	AnesthesiaBaseUnitCt Long 4
	ChargePerUnit Currency 8
	LnSvcsCt Decimal 16
	Mod01 Text 2
	Mod02 Text 2
	Mod03 Text 2
	Mod04 Text 2
	Mod05 Text 2
	LnPOS Text 2
	LnProvSt Text 2
	LnProvSpecialty Text 2
	LnGroupNpi Text 10
	LnHcfaSpecCd Text 2
	PayerReceiptDt Date/Time 8
	CarrDupCheck Text 21
	DMEOrderingNPI Text 10
	BusinessSegId Text 16
	TOB Text 3
	MqaRicCd Text 1
	MspFlag Long 4
	RevLineCt Long 4
	DataType Text 5
	ClmGuid Guid 16
	cnlyClaimNum Text 30
	LnTypSvcCd Text 2
	PpsInd Text 1
	WageAdjCoinsAmt Currency 8
	CashDedAmt Currency 8
	initdeterminationdt Date/Time 8
	AdmitDiagVrsnCd Text 1
	PrincipalDiagVrsnCd Text 1
	LnDiagVrsnCd Text 1
	ECodeVrsnCd Text 1
	NDC Text 24
