v_ALJ_732_Form

Fields
	HearingPackageName Text 50
	AppellantContactFullName Text 50
	AppellantName Text 100
	ApFaxNum Text 30
	ApPhoneNum Text 30
	ConnollyContactName Memo 0
	ConnPhoneNum Text 15
	ConnFaxNum Text 15
	ConnEmail Text 30
	ConnollyHearingParticipantName Text 31
	PartTitle Text 5
	PartDegree Text 5
	ConnollyHearingParticipantName2 Text 31
	PartTitle2 Text 5
	PartDegree2 Text 5
	PartList Text 89
	PartPhoneNum Text 30
	PartPasscode Text 10
	Part732Info Text 122
	Part732Phone Text 50
	LegalAssistant Text 71
	JudgeName Text 61
	JudgeFaxNumber Text 30
	JudgePhoneNumber Text 30
	HearingPhone Text 31
	HearingPasscode Text 12
	HearingPhoneSource Text 8
	ALJNoticeReceivedDate Date/Time 8
	FaxDate Date/Time 8
	HearingDate Date/Time 8
	PTTime Date/Time 8
	folderName Memo 0
	EditNote Memo 0
	UpdatedFaxDate Date/Time 8
	AppellantFolderName Text 100
	PartyStatus Text 10
	TestimonyType Text 20
	NonPartyPosPaper Text 3
	NonPartyTest Text 3
	NonPartyPoints Text 3
	PartyPosPaper Text 3
	PartyTest Text 2
	PartyPoints Text 3
	PartyTestOr Text 3
	PartyDisc Text 3
	PartyInfo Text 3
	PartyWitn Text 3
