v_AUDITCLM_Dtl

Fields
	CnlyClaimNum Text 30
	LineNum Long 4
	RevDt Date/Time 8
	RevCd Text 4
	HCPCSCd Text 5
	Mod01 Text 2
	Mod02 Text 2
	Units Long 4
	ChargePerUnit Currency 8
	UnitType Text 1
	LnChargeAmt Currency 8
	LnReimbAmt Currency 8
	Adj_Ind Text 1
	Adj_HCPCS Text 5
	Adj_Units Long 4
	Adj_ProjectedSavings Currency 8
	Adj_ConceptID Text 10
	Adj_VulnerabilityCd Text 10
	Mod03 Text 2
	Mod04 Text 2
	Mod05 Text 2
	LnProvNum Text 16
	LnProvNpi Text 10
	LnProvSt Text 2
	LnProvSpecialty Text 5
	LnHcfaSpecCd Text 3
	LnGroupNpi Text 10
	LnProvTin Text 9
	LnClmFromDt Date/Time 8
	LnClmThruDt Date/Time 8
	LnPOS Text 2
	LnDiagCd Text 5
	AnsiCd01 Text 5
	AnsiCd02 Text 5
	AnsiCd03 Text 5
	AnsiCd04 Text 5
	AnesthesiaBaseUnitCt Long 4
	BetosCd Text 5
	NDC Text 11
	LnAllowedAmt Currency 8
	LnNonCoveredAmt Currency 8
	LnBenePdAmt Currency 8
	LnCoinsAmt Currency 8
	LnCOBAmt Currency 8
	DMEPurchasePrice Currency 8
	AutoId Long 4
	Adj_Mod01 Text 2
	Adj_Mod02 Text 2
	Adj_Mod03 Text 2
	Adj_Mod04 Text 2
	Adj_Mod05 Text 2
	AccountID Long 4
