v_LETTER_AUTOMATION_OPS_ClaimDetailForInstances

Fields
	CnlyClaimNum Text 30
	ICN Text 30
	OriginalICN Text 30
	ClmStatus Text 5
	ClmStatusDesc Text 255
	DataType Text 5
	PayerNum Text 5
	ProvStCd Text 2
	CAN Text 35
	BIC Text 8
	EquatedBic Text 8
	PrincipalDiag Text 7
	ClmFromDt Date/Time 8
	ClmThruDt Date/Time 8
	ClmTotalChgs Currency 8
	ReimbAmt Currency 8
	TOB Text 3
	Adj_AuditNum Long 4
	Adj_Auditor Text 50
	Adj_ReviewType Text 10
	Adj_ConceptId Text 10
	Adj_VulnerabilityCd Text 10
	Adj_DRG Text 5
	Adj_ProjectedSavings Currency 8
	Adj_RecoveryAmt Currency 8
	Adj_Can Text 30
	Adj_Bic Text 8
	Adj_From Text 30
	Adj_To Text 30
	Adj_CreateDate Date/Time 8
	LastUpDt Date/Time 8
	LastUpUser Text 50
	LetterType Text 50
	LetterReqDt Text 10
	Held Text 1
	ManualOverRide Boolean 1
	InProgress Text 1
	AccountId Long 4
	DynamicInstanceId Text 80
	InstanceID Text 100
	Status Text 2
	ContractID Long 4
