v_SCANNING_Quick_Image_Log

Fields
	SessionID Text 30
	UserID Text 50
	CreateDt Date/Time 8
	RequestNum Text 80
	SeqNo Long 4
	CnlyClaimNum Text 30
	ICN Text 30
	CnlyProvId Text 30
	ProvNum Text 30
	ProvName Text 255
	LetterReqDt Text 10
	MemberName Text 255
	DOB Date/Time 8
	MedicalRecordNum Text 30
	PatCtlNum Text 38
	AdmitDate Text 10
	DischargedDate Text 10
	ClmFromDt Text 10
	ClmThruDt Text 10
	AuditNum Long 4
	ImageName Text 255
	ImageType Text 10
	ImageTypeDisplay Text 10
	ScannedDt Date/Time 8
	ClientFileName Text 255
	ReceivedMeth Text 20
	ReceivedDt Date/Time 8
	Carrier Text 50
	TrackingNum Text 255
	ErrMsg Text 255
	AccountID Long 4
	ImportFlag Text 1
	FastScanFolder Text 50
	FastScanStatusCd Text 50
	FastScanNoMatchReason Text 100
	FastScanStatusCdDt Text 10
