RPT_SELECT_Automated_Claims

Fields
	ContractID Long 4
	ConceptID Text 50
	ConceptLevel Text 1
	DataType Text 50
	ProvStCd Text 50
	PayerNum Text 5
	PayerName Text 30
	ProvNum Text 50
	DRG Text 3
	HCPCSCd Text 50
	CnlyClaimNum Text 30
	LineNum Long 4
	ReimbAmt Currency 8
	Adj_ProjectedSavings Currency 8
	Adj_Units Long 4
	ReviewType Text 1
	ConceptStatus Long 4
	RefreshFinancials Boolean 1
	ICN Text 23
	PPSInd Text 1
	SchedPmtDt Date/Time 8
	InitDeterminationDt Date/Time 8
	ClmFromDt Date/Time 8
	Can Text 16
	EquatedBic Text 2
	Bic Text 2
	BeneSexCd Text 1
	ClaimProvNPI Text 10
	ProvHdrNPI Text 30
	SelectCd Text 100
	ConceptReviewType Text 1
	SelectID Long 4
	OtherOne Text 30
	CnlyProvId Text 30
	ClmThruDt Date/Time 8
	ConceptDesc Text 100
	HCPCSShortDescription Text 100
	DiagCds Memo 0
	user01 Text 50
	user02 Text 50
	user03 Text 50
	date01 Date/Time 8
	date02 Date/Time 8
	date03 Date/Time 8
	dec01 Decimal 16
	dec02 Decimal 16
	dec03 Decimal 16
	Adj_ind Text 1
	ConceptVersion Text 10
	ConceptRunDt Date/Time 8
	Adj_Mod01 Text 2
	Adj_Mod02 Text 2
	Adj_Mod03 Text 2
	Adj_Mod04 Text 2
	Adj_Mod05 Text 2
	RevCd Text 4
	Mod01 Text 2
	Mod02 Text 2
	Mod03 Text 2
	Mod04 Text 2
	Mod05 Text 2
	LnDiagCd Text 7
	Units Decimal 16
	LnReimbAmt Currency 8
	LnChargeAmt Currency 8
	LnAllowedAmt Currency 8
	LnTypSvcCd Text 2
	RevDt Date/Time 8
	LnPOS Text 2
	LnProvNum Text 10
	LnProvNpi Text 10
	LnProvSt Text 2
	LnProvSpecialty Text 2
	LnHcfaSpecCd Text 2
	LnGroupNpi Text 10
	LnProvTin Text 10
	LnClmFromDt Date/Time 8
	LnClmThruDt Date/Time 8
	AnsiCd01 Text 5
	AnsiCd02 Text 5
	AnsiCd03 Text 5
	AnsiCd04 Text 5
	UnitType Text 1
	ChargePerUnit Currency 8
	AnesthesiaBaseUnitCt Long 4
	BetosCd Text 5
	NDC Text 24
	LnNonCoveredAmt Currency 8
	LnBenePdAmt Currency 8
	LnCoinsAmt Currency 8
	LnCOBAmt Currency 8
	DMEPurchasePrice Currency 8
	RevCntrDedCoinsCd Text 1
	RevConsolidatedBillCd Text 2
	LnSvcsCt Decimal 16
	BenePartBDedAmt Currency 8
	CarrDupCheck Text 1
	ProvZip Text 9
	ParInd Text 1
	LineConsBillingIndCd Text 1
	AddlClmDocIndCd Text 1
	RdcdPmtAsstCd Text 1
	TrtmtAuth Text 18
	AdmitDiag Text 7
	FISS_AdmitDiag Memo 0
