v_CONCEPT_NewIssueProposal_INTERNAL

Fields
	ConceptID Text 10
	ConceptDesc Memo 0
	ConceptLogic Memo 0
	ConceptRationale Memo 0
	ConceptLevel Text 1
	ConceptStatus Long 4
	VulnID Text 10
	OpportunityType Text 1
	ReviewType Text 10
	ConceptSQL Text 255
	Auditor Text 50
	RiskFactor Long 4
	CostFactor Long 4
	MaxChartRequest Long 4
	LastUpDt Date/Time 8
	LastUpUser Text 50
	AccountID Long 4
	NoteID Long 4
	DataType Text 5
	DateSubmitted Date/Time 8
	ProviderTypeID Long 4
	ConceptReferences Memo 0
	Comments Memo 0
	TimeframeReference Text 25
	ReferralFlag Text 1
	ReferralEntity Text 50
	ConceptIndicator Text 10
	Hyperlink Memo 0
	ErrorCode Text 10
	ConceptPriority Text 5
	AdditionalInfo Memo 0
	ConceptSource Text 50
	ClientIssueNum Text 50
	ViantIssueNum Text 50
	ConceptClaimCount Long 4
	ConceptPotentialValue Currency 8
	SampleClaimClount Long 4
	SamplePotentialValue Currency 8
	LiabilitySource Memo 0
	CopyOfReference Memo 0
	DetailedReviewRationale Memo 0
	MedicalRecords Memo 0
	SampleOfClaims Memo 0
	EditParameters Memo 0
	OtherDocumentation Memo 0
	CreateDate Date/Time 8
	ErrorCode2 Text 12
	ToRun Text 1
	ConceptGroup Text 255
	LOB Text 255
	ReviewType1 Text 150
	OpportunityType1 Text 25
	ReferralFlag1 Text 3
	PriorityDescription Text 25
	ResubmittedDt Date/Time 8
	ProviderDesc Memo 0
	ErrorDescription Memo 0
	Error2Description Memo 0
