AUDITCLM_INT_Hdr

Fields
	DataType Text 5
	PayerNum Text 5
	ICN Text 23
	OriginalIcn Text 23
	QueryCd Text 1
	ProvNum Text 16
	CnlyProvID Text 30
	ProvStCd Text 2
	ProvSpecCd Text 5
	ProvNpi Text 20
	MedicalRecordNum Text 17
	PatCtlNum Text 20
	Can Text 16
	Bic Text 2
	EquatedBic Text 2
	BeneBirthDt Date/Time 8
	BeneStCD Text 2
	BeneSexCd Text 1
	BeneRaceCd Text 1
	PatSurname Text 6
	PatFirstInit Text 1
	PatMidInit Text 1
	NchPatientStatus Text 1
	DRG Text 3
	AdmitDiag Text 7
	PrincipalDiag Text 7
	LOS Long 4
	IpAdmitType Text 1
	IPAdmitDt Date/Time 8
	IPDischargeDt Date/Time 8
	ClmFromDt Date/Time 8
	ClmThruDt Date/Time 8
	SchedPmtDt Date/Time 8
	PayerReceiptDt Date/Time 8
	ClmTotalChgs Currency 8
	AllowedChgAmt Currency 8
	ReimbAmt Currency 8
	ProvPdAmt Currency 8
	BenePdAmt Currency 8
	COBAmt Currency 8
	COBCarrierCd Text 1
	Deductible Currency 8
	BeneCoins Currency 8
	DRGOutlierPmt Currency 8
	DischargeStatus Text 2
	ClmDispositionCd Text 2
	TOB Text 3
	ClmFreqCd Text 3
	OpTransType Text 1
	IPOutlierIndicator Text 1
	AttendingPhysician Text 16
	AttendingNpi Text 10
	OprtgUPIN Text 16
	OprtgNpi Text 16
	ReferPhysUPIN Text 6
	ReferPhysNPI Text 10
	OrderingUPIN Text 6
	OrderingNPI Text 10
	OthProvUPIN Text 6
	OthProvNpi Text 10
	ECode Text 7
	PricerReturnCd Text 2
	LoadDt Date/Time 8
	CnlyClaimNum Text 30
	ClmGuid Guid 16
	accountid Long 4
	autoid Long 4
	PpsInd Text 1
	IpAdmitSource Text 1
	CnlyClaimId Text 30
	MspFlag Long 4
	TrtmtAuth Text 18
	ReviewPeriod Text 15
	InitDeterminationDt Date/Time 8
	TherapyEdit Text 20
	AdmitDiagVrsnCd Text 1
	PrincipalDiagVrsnCd Text 1
	PrincipalProcVrsnCd Text 1
	ECodeVrsnCd Text 1
	ContractID Long 4
	ICDVersionCdFlag Integer 2
