v_QUEUE_Hdr

Fields
	MRReceived_Age Long 4
	MRValidationDt Date/Time 8
	ReviewDueDate Text 10
	MRReceivedDt Date/Time 8
	DaysToReview Long 4
	ReconReceived_Age Long 4
	DRG Text 3
	CnlyClaimNum Text 30
	ClmStatus Text 5
	ClmStatusDesc Text 255
	ICN Text 30
	ProvStCd Text 2
	MedicalNecessity Text 1
	CnlyProvID Text 30
	ProvName Text 255
	DataType Text 5
	InactiveDays Long 4
	ExceptionType Text 5
	QueueType Text 5
	QueueDesc Text 255
	PayerNum Text 5
	Payername Text 50
	QueueStatus Text 10
	MemberName Text 40
	MemberDOB Date/Time 8
	Adj_ConceptID Text 10
	Adj_DRG Text 5
	Adj_VulnerabilityCd Text 10
	AssignedFrom Text 50
	AssignedTo Text 50
	AssignedDate Date/Time 8
	TotalChargeAmt Currency 8
	Orig_ReimbAmt Currency 8
	Adj_ReimbAmt Currency 8
	Adj_ProjectedSavings Currency 8
	Adj_ClosedDt Date/Time 8
	HoldDate Date/Time 8
	QueueAgeGroup Text 15
	AR_AgeGroup Text 15
	AR_Error Text 1
	CreateDt Date/Time 8
	QueueEntryDt Date/Time 8
	NextReviewDt Date/Time 8
	MaxThresholdDt Date/Time 8
	LastUpdate Date/Time 8
	UpdateUser Text 50
	NoteID Long 4
	BatchDt Text 10
	AuditNum Long 4
	AccountID Long 4
	ReviewType Text 10
	ARDate Date/Time 8
	AppealDt Text 26
	AppealOutcome Memo 0
	SubStatus Text 10
	ClaimGroup Text 255
	LOB Text 50
	OCRStatus Text 6
	CompanyName Text 100
	ProvStat Text 14
	Supp Text 20
	SendPayerExl Memo 0
	Bookmarked Long 4
	Outstanding_Desc Memo 0
